#Site configuration
title: Read
name:  Maria Pettyjohn
author: Anthony Stark
work:  Developer
year: 2018

# Navigation
nav1: "About"
nav2: "Education"
nav3: "Publications"
nav4: "Teaching"
nav5: "Download CV"
nav6: "Contact Me"

# Section1
sec1: "Maria Pettyjohn"
sec2: "Master's Student - Unversity of Alberta - Department of Physics"
sec3: "I am a Master's student at the University of Alberta, specialising in astrophysics. I work with Professor Erik Rosolowsky studying the clouds in space that form stars and planets. My research focuses on the determining how the abundances of prebiotic molecules change with local enivronment of the cloud."

# Section 2
sec4: "Education"
sec5: ""
icon1: "fas fa-code"
icont1: "Write all the code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Section 3
sec6: "Publications"
sec7: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec8: "Possibly broke spacetime"
sec9: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec10: "Terraformed a small moon"
sec11: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec12: "Snapped dark matter in the wild"
sec13: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Section 4
sec14: "Publications"
sec15: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec16: "Possibly broke spacetime"
sec17: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec18: "Terraformed a small moon"
sec19: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec20: "Snapped dark matter in the wild"
sec21: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Section 5
sec14: "Teaching"
sec15: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec16: "Possibly broke spacetime"
sec17: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec18: "Terraformed a small moon"
sec19: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec20: "Snapped dark matter in the wild"
sec21: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Section 6
sec22: "Download CV"
sec23: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec24: "Possibly broke spacetime"
sec25: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec26: "Terraformed a small moon"
sec27: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec28: "Snapped dark matter in the wild"
sec29: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Social Links
facebook: username
twitter:  username
#google: username
#instagram: username
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
github: username
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
keybase: username
email: test@gmail.com

